version: '3.9'

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_USER: shoes_user
      MYSQL_PASSWORD: shoes_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-new:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  shoesstore:
    image: walterbaya/shoestore:latest
    container_name: shoesstore-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://mysql:3306/shoes_store?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER: shoes_user
      DB_PASSWORD: shoes_password
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data-new:
